### ISSUE TITLE
Fix alert tab

### ISSUE THREAD

**Issue by bacloud22** [bacloud22/WeatherVenue#20]
Alert tab as in this picture (in red), is not visible. It is broke probably because of CSS

![Capture_map](https://github.com/user-attachments/assets/41885397-d699-4aa3-a706-2ca6c5f6028f)

**Comment by CalebCooperDev** [comment]
I'd be willing to take a look at this

**Comment by CalebCooperDev** [comment]
Greetings!  I'm grateful to be included in this project.  I am having trouble getting this to run on my machine.  I've got redis installed and I can ping the server but when I try to run the app with node server.js I get this {"statusCode":500,"error":"Internal Server Error","message":"engine.configure is not a function"}

I am unsure how to proceed.

**Comment by bacloud22** [comment]
I really don't know!

**Comment by CalebCooperDev** [comment]
So that is how I'm supposed to start it.  I wasn't sure cuz I've never used redis before

**Comment by bacloud22** [comment]
Just don't. You can contribute to other projects.
