### ISSUE TITLE
Fix Github action that runs Cypress UI test

### ISSUE THREAD

**Issue by bacloud22** [bacloud22/WeatherVenue#5]
The Github action is supposed to compile and run the projet. The action was made on early stage of the web-app, and many things changes since then. It does not work anymore, (example: gulp is no longer used).

**Comment by Lemeri123** [comment]
assign this to me as well please @bacloud22

**Comment by bacloud22** [comment]
Yep.

**Comment by bacloud22** [comment]
do you have experience with GH actions ? not easy I guess ?

**Comment by Lemeri123** [comment]
Yea its quite not easy but I have been able to update the gitbub actions thou I still get a couple of errors that mark the whole code and thats what am still trying to resolve.
![Screenshot 2024-12-04 182016](https://github.com/user-attachments/assets/633e80ba-d2eb-4aa7-a693-f04c53e9ede6)

**Comment by bacloud22** [comment]
Ok good luck 🤞

**Comment by bacloud22** [comment]
could you take a look on https://github.com/bacloud22/WeatherVenue/issues/23 and https://github.com/bacloud22/WeatherVenue/tree/main/cypress @Lemeri123 ?
Thank you

**Comment by Lemeri123** [comment]
sure thing
