### ISSUE TITLE
Decouple Gmap.js and client side javascript files

### ISSUE THREAD

**Issue by bacloud22** [bacloud22/WeatherVenue#58]
All files are loaded in different pages, It would be better to write a modular code instead. Especially the main file which is [GMap](https://github.com/bacloud14/WeatherVenue/blob/master/src/js/GMap.js)

**Comment by susham** [comment]
@bacloud22  Is this issue still open?  I would like to work on it.

**Comment by bacloud22** [comment]
Yes @susham 
Feel free to contribute

**Comment by bacloud22** [comment]
Hi @susham 
Any follow up?
Good luck 🤞

**Comment by susham** [comment]
@bacloud22 I didn't get a chance to work on this issue. Will work on it this week and update

**Comment by susham** [comment]
@bacloud22  I am still trying to understand the codebase would like to understand, what do you mean by "Decouple Gmap.js and other client side javascript files"

Can you please give an example?

**Comment by bacloud22** [comment]
Hello Susham,
So in JS as in many languages, we have structures, like Classes, functions, ...
I just meant a "better code", more decoupled as You can see now it is a mono block and not easy to understand,
Anything else like variable naming, code style etc etc, could be refactored.
Good luck !
