### ISSUE TITLE
Fix bootstrap dropdown menu

### ISSUE THREAD

**Issue by bacloud22** [bacloud22/WeatherVenue#8]
Bootstrap bundle is used although drop down is not working
![image](https://github.com/user-attachments/assets/6d841e87-a4f5-4a24-a0f9-898fba4b3a49)

**Comment by Choucheneeee** [comment]
I’m interested in working on it.If this issue is still available, could you please assign it to me?

**Comment by bacloud22** [comment]
hi @Choucheneeee , yes ofc please go ahead.

**Comment by abderrahim-ben** [comment]
Run Redis server on default port, fill in .env variables:
```ts
NODE_ENV=localhost
GOOGLE_MAPS_API_KEY=
OPENWEATHERMAP_API_KEY=
```
both on root folder and inside client folder.

For `OPENWEATHERMAP_API_KEY` you can put whatever you want it does not matter, I'm using a fake variable here:
https://github.com/bacloud22/WeatherVenue/blob/main/libs/consts/fakeOneCallApiResponse.js 

thank you.

**Comment by bacloud22** [comment]
Run Redis server on default port, fill in .env variables:
```ts
// root folder
NODE_ENV=localhost
GOOGLE_MAPS_API_KEY=
OPENWEATHERMAP_API_KEY=
```

```ts
// client
GOOGLE_MAPS_API_KEY=
DEFAULT_LAT=48.86
DEFAULT_LNG=2.34
CENTER_LOCATION=paris
```

both on root folder and inside client folder.

For `OPENWEATHERMAP_API_KEY` you can put whatever you want it does not matter, I'm using a fake variable here:
https://github.com/bacloud22/WeatherVenue/blob/main/libs/consts/fakeOneCallApiResponse.js 

thank you.

**Comment by bacloud22** [comment]
Hi 👋 
Any follow up?

**Comment by bacloud22** [comment]
Hi 👋 
Any follow up?

**Comment by bacloud22** [comment]
please @Choucheneeee  raise a new PR for updating README
Thank you @Choucheneeee
